name: nox-plugin-risk-register
version: 0.1.0
track: policy-governance
description: Automated technical risk identification and categorization for codebases
tools:
  - name: scan
    description: Scan source code for technical risks including debt, deprecated APIs, single points of failure, and complexity
